import type { Metadata } from "next";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";

import { pretendard } from "@/ui/font";
import PageEnterAni from "@/ui/components/PageEnterAni";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} pretendard`}>
        <PageEnterAni />
        <ViewTransitions>{children}</ViewTransitions>
      </body>

    </html>
  );
}
